### ISSUE TITLE
[Intro to iOS] [CodePath iOS BootCamp]

### ISSUE THREAD

**Issue by bryanmclellan** [bryanmclellan/tomatoes#1]
Finished the Rotten Tomatoes client. Please review. /cc @thecodepath

**Comment by timothy1ee** [comment]
Bryan, next time can you start with the template readme file? That makes it easier on the graders.

**Comment by codepathreview** [comment]
:+1: very nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API.
Detailed comments:
- Nice code styling. Check out these Swift style guides:
  - [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
  - [Github Swift Style Guide](https://github.com/github/swift-style-guide)
- Nice work implementing the Movie model.
- Your custom Movie cell should have a property called `movie`. In the custom setter of `movie`, you should configure the various labels and images. This decouples your custom cell views from the table view controllers. (MVC model)
- Nice work setting up the proper modes for the images so that they are not stretched.
- Nice work implementing the error message on network failure.
- On the details view, it is hard to read the text. You could make the background darker or increase the alpha value. 
- Cool idea of including the Rotten Tomatoes logo.
- Well done on implementing extensions.
- Useful display of ratings.
